### ISSUE TITLE
[Feature] Create favorites menu

### ISSUE THREAD

**Issue by rogue-cyborg** [rogue-cyborg/color-generator#18]
I just thought about this and I feel like it could be a good problem for someone to solve for Hacktoberfest:
1. Create a favorites menu that loads favorites when opened.
a. My idea was to put a heart icon in the nav bar that pops open a menu or modal
2. Allow users to save a palette as a favorite.
a. This could include a text input for the user to name the palette.
3. Save the palette in [localStorage ](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) since this site is hosted statically and we can't use a database.

Remember to think about how this will work and look on mobile devices!

**Comment by kushaggarwal** [comment]
i would like to work on this problem

**Comment by rogue-cyborg** [comment]
@kushaggarwal Great. Just submit a pull request when you're done. Remember to include a description of the changes you've made in the pull request.

**Comment by kushaggarwal** [comment]
Okay sure thank you 
Is it fine if I submit it by tomorrow

**Comment by rogue-cyborg** [comment]
@kushaggarwal I don't have any time restraints - this project is for learning. Take your time.

**Comment by kushaggarwal** [comment]
Okay Thank you very much

**Comment by jaisoneji** [comment]
Hey! I have worked on this problem and it is completed.I have submitted Pull request to you with the description of changes i have made.

**Comment by rogue-cyborg** [comment]
For anyone looking at this, the [current PR (#23)](https://github.com/rogue-cyborg/color-generator/pull/23) for this doesn't add a lot of value. Anyone else is welcome to submit a PR with a different implementation.
